services:
  app:
    build: .
    container_name: lexai-app
    ports:
      - "5000:5000"
    environment:
      - MOCK_MODE=true # Set to false to use actual model (requires GPU and weights loaded)
    volumes:
      - ./lora_model:/app/lora_model
      - ./llama_base_model:/app/llama_base_model
      - ./Act_Elastic search:/app/Act_Elastic search
      - ./templates:/app/templates
      - ./dataset.json:/app/dataset.json
      - ./sections.json:/app/sections.json

